# .github/workflows/release.yml

name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile pr_stats_calculator.py

    - name: Archive the build output (Linux & macOS)
      if: matrix.os != 'windows-latest'
      run: |
        zip -r pr_stats_calculator_${{ matrix.os }}.zip dist/
      continue-on-error: true

    - name: Archive the build output (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        powershell Compress-Archive -Path dist\pr_stats_calculator.exe -DestinationPath pr_stats_calculator_windows.zip

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-build
        path: |
          pr_stats_calculator_*.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: ubuntu-latest-build

    - name: Download Windows artifact
      uses: actions/download-artifact@v3
      with:
        name: windows-latest-build

    - name: Download macOS artifact
      uses: actions/download-artifact@v3
      with:
        name: macos-latest-build

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          pr_stats_calculator_ubuntu-latest.zip
          pr_stats_calculator_windows.zip
          pr_stats_calculator_macos-latest.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
