# .github/workflows/release.yml

name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow on version tags, e.g., v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile prstats/pr_stats_calculator.py

    - name: Archive the build output
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          zip -r pr_stats_calculator_linux.zip dist/;
        elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          powershell Compress-Archive -Path dist/pr_stats_calculator.exe -DestinationPath pr_stats_calculator_windows.zip;
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          zip -r pr_stats_calculator_macos.zip dist/;
        fi

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-build
        path: |
          pr_stats_calculator_linux.zip
          pr_stats_calculator_windows.zip
          pr_stats_calculator_macos.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.os }}-build

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          pr_stats_calculator_linux.zip
          pr_stats_calculator_windows.zip
          pr_stats_calculator_macos.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
